name: Bundlewatch

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: read

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run dist
        run: npm run dist

      - name: Run bundlewatch
        uses: jackyef/bundlewatch-gh-action@0.2.1
        with:
          branch-base: main
          bundlewatch-config: .bundlewatch.config.json
          bundlewatch-github-token: "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}"
